version: "3"

services:
  server:
    build:
      context: .docker/php/8.1-apache
      dockerfile: Dockerfile
    ports:
      - "85:80"
    volumes:
      - .:/var/www/html
    networks:
      - mynetwork

    ####> doctrine/doctrine-bundle ###
  database:
    image: mysql
    platform: linux/arm64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony
    ports:
      - "33060:3306"
    env_file:
      - .env
    networks:
      - mynetwork

  composer:
    image: composer/composer
    command: composer install
    volumes:
      - ./:/app
    networks:
      - mynetwork

networks:
  mynetwork:
